from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_page, name='login'),
    path('login', views.login_page),
    path('meetings/<int:meeting_id>/', views.meeting_page, name='meeting_page'),
    path('meetings/<int:meeting_id>', views.meeting_page),
    path('api/log/', views.log_action, name='log_action'),
    path('api/log', views.log_action),
    path('api/ping/', views.ping, name='ping'),
    path('api/ping', views.ping),
    path('api/meetings/', views.meetings, name='meetings'),
    path('api/meetings', views.meetings),
    path('api/meetings/<int:meeting_id>/', views.meeting_detail, name='meeting_detail'),
    path('api/meetings/<int:meeting_id>', views.meeting_detail),
    path('api/meetings/<int:meeting_id>/photos/', views.meeting_photos, name='meeting_photos'),
    path('api/meetings/<int:meeting_id>/photos', views.meeting_photos),
    path('api/meetings/<int:meeting_id>/photos/<int:photo_id>/', views.delete_photo, name='delete_photo'),
    path('api/meetings/<int:meeting_id>/photos/<int:photo_id>', views.delete_photo),
    path('api/auth/status/', views.auth_status, name='auth_status'),
    path('api/auth/status', views.auth_status),
    path('api/auth/login/', views.auth_login, name='auth_login'),
    path('api/auth/login', views.auth_login),
    path('api/auth/logout/', views.auth_logout, name='auth_logout'),
    path('api/auth/logout', views.auth_logout),
    path('api/tags/', views.tags_list, name='tags_list'),
    path('api/tags', views.tags_list),
    path('api/tags/manage/', views.tags_manage, name='tags_manage'),
    path('api/tags/manage', views.tags_manage),
    path('api/tags/<int:tag_id>/', views.tag_detail, name='tag_detail'),
    path('api/tags/<int:tag_id>', views.tag_detail),
    path('api/meetings/<int:meeting_id>/tags/<int:tag_id>/', views.meeting_tags, name='meeting_tags'),
    path('api/meetings/<int:meeting_id>/tags/<int:tag_id>', views.meeting_tags),
]