# Generated by Django 6.0.3 on 2026-03-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_meeting_notes_meetingphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('meetings', models.ManyToManyField(blank=True, related_name='tags', to='activity.meeting')),
            ],
        ),
    ]
