# Generated by Django 6.0.3 on 2026-03-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
